# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc7eed685f2f529c2e8d1200cdcc244157d47b8bdca499a9cae4cebe2e90005f9f05309ec9009750f23048a87180edc0f8dcbcc427a663bb1315911c10083af

test:
  secret_key_base: 823253b9bb6311c0f800f87f89f47fe840dec5654c9a3b9907d994b2ddf4fe60f4b3cbae519289474ef597c895b8804b023cb4b7fcfd85c7f0d549b7b7d7db35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
